# Generated by Django 5.2.9 on 2025-12-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Nutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('azucares', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'nutricional',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caducidad', models.DateField()),
                ('elaboracion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('eliminado', models.DateTimeField(blank=True, null=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
                ('nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.nutricional')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
    ]
