# Generated by Django 5.2.5 on 2025-12-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorias',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='producto',
        ),
    ]
