# Generated by Django 5.2.5 on 2025-12-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categorias_table_alter_productos_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='categorias',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productos',
            table=None,
        ),
    ]
