# Generated by Django 5.2.5 on 2025-12-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_categorias_options_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorias',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='producto',
        ),
    ]
