# Generated by Django 4.1 on 2025-12-10 05:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_categorias_table_alter_productos_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientosinventario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.productos'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=7),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='azucares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='calorias',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='carbohidratos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='grasas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nutricional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='inventario.nutricional'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_actual',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_minimo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='categorias',
            index=models.Index(fields=['nombre'], name='categoria_nombre_74de13_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['productos'], name='movimientos_product_462841_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosinventario',
            index=models.Index(fields=['fecha'], name='movimientos_fecha_c137fc_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['nombre'], name='producto_nombre_38c699_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['precio'], name='producto_precio_e7989f_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['caducidad'], name='producto_caducid_33d908_idx'),
        ),
    ]
