# Generated by Django 4.1 on 2025-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_movimientosinventario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricional',
            name='identificador',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
