# Generated by Django 4.1 on 2025-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_nutricional_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código opcional único para ventas/lookup rápido.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], db_index=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['codigo'], name='producto_codigo_6cda58_idx'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['stock_actual'], name='producto_stock_a_3070ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(check=models.Q(('stock_actual__gte', 0)), name='ck_producto_stock_actual_no_negativo'),
        ),
    ]
