# Generated by Django 4.1 on 2025-12-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_productos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nutricional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.nutricional'),
        ),
    ]
