# Generated by Django 5.2.9 on 2025-12-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total_sin_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal_venta', models.CharField(max_length=10)),
                ('folio', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientes')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
