# Generated by Django 5.2.5 on 2025-12-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='venta',
        ),
    ]
