# Generated by Django 5.2.5 on 2025-12-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_clientes_table_alter_ventas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name_plural': 'Detalle_ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelTable(
            name='clientes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ventas',
            table=None,
        ),
    ]
