# Generated by Django 5.2.5 on 2025-12-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_clientes_options_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='venta',
        ),
    ]
