# Generated by Django 4.1 on 2025-12-11 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_options_alter_ventas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveIndex(
            model_name='ventas',
            name='venta_fecha_ed3809_idx',
        ),
        migrations.RemoveIndex(
            model_name='ventas',
            name='venta_folio_563a7f_idx',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
